# NFL MVP 2024 using Data Analysis Tools

## First we import the Quarterbacks.

### Importing the first libraries we are using:

In [4]:
from bs4 import BeautifulSoup
import requests

### Next we define 3 variables for the sake of making things easier. 
### The first variable "url" is the website's URL we are scrapping the data from in text form.
### The second variable "page" sends a request to the website we defined using the "url" variable we defined first.
### The "soup" variable contains a function that gets the HTML code from the website and help us utilize it for scrapping.

In [7]:
url = 'https://www.nfl.com/stats/player-stats/'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

### We define a new variable that will contain the information obtained using the method "find_all" from BeautifulSoup library.

In [9]:
find_headers = soup.find_all('th', class_='header')
#print(find_headers)

### Next we create a new variable that will contain a list with a FOR loop which will help us obtain the Headers from the table located in the website.

In [13]:
find_header = [header.text.strip() for header in find_headers]
print(find_header)

['Player', 'Pass Yds', 'Yds/Att', 'Att', 'Cmp', 'Cmp %', 'TD', 'INT', 'Rate', '1st', '1st%', '20+', '40+', 'Lng', 'Sck', 'SckY']

### We import the Pandas library to create a new DataFrame with the information obtained from the website.

In [16]:
import pandas as pd

### Creating the DataFrame using pandas.

In [19]:
df = pd.DataFrame(columns = find_header)
df

Empty DataFrame
Columns: [Player, Pass Yds, Yds/Att, Att, Cmp, Cmp %, TD, INT, Rate, 1st, 1st%, 20+, 40+, Lng, Sck, SckY]
Index: []

### Next we create a new variable that will get us all the information contained in the "tr" brackets of the HTML from the website.

In [22]:
#find_content = soup.find_all('tr')
#print(find_content)
column_data = soup.find_all('tr')
#column_data

### For this part we create a nested FOR loop to get the information from the website's data table.

In [25]:
for row in column_data[1:]: #For Loop that skips the first row (headers)
    row_data = row.find_all('td') #We get the information contained inside the td brackets
    individual_row_data = [data.text.strip() for data in row_data] # Creating a list using a nested for loop to get each element in the table
    #print(individual_row_data)
    length = len(df) #We get the length of the dataframe to add the information obtained to the end of the dataframe 
    df.loc[length] = individual_row_data # in order to not replace the existing one

# Next we import Running Backs

In [35]:
url = 'https://www.nfl.com/stats/player-stats/category/rushing/2024/reg/all/rushingyards/desc'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

In [37]:
find_headers = soup.find_all('th', class_='header')
#print(find_headers)

In [39]:
find_header = [header.text.strip() for header in find_headers]
print(find_header)

['Player', 'Rush Yds', 'Att', 'TD', '20+', '40+', 'Lng', 'Rush 1st', 'Rush 1st%', 'Rush FUM']

In [41]:
df2 = pd.DataFrame(columns = find_header)
df2

Empty DataFrame
Columns: [Player, Rush Yds, Att, TD, 20+, 40+, Lng, Rush 1st, Rush 1st%, Rush FUM]
Index: []

In [59]:
#find_content = soup.find_all('tr')
#print(find_content)
column_data = soup.find_all('tr')
#column_data

In [53]:
for row in column_data[1:]: #For Loop that skips the first row (headers)
    row_data = row.find_all('td') #We get the information contained inside the td brackets
    individual_row_data = [data.text.strip() for data in row_data] # Creating a list using a nested for loop to get each element in the table
    #print(individual_row_data)
    length = len(df2) #We get the length of the dataframe to add the information obtained to the end of the dataframe 
    df2.loc[length] = individual_row_data # in order to not replace the existing one

# Importing Wide Receivers

In [82]:
url = 'https://www.nfl.com/stats/player-stats/category/receiving/2024/reg/all/receivingreceptions/desc'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

In [83]:
find_headers = soup.find_all('th', class_='header')
#print(find_headers)

In [84]:
find_header = [header.text.strip() for header in find_headers]
print(find_header)

['Player', 'Rec', 'Yds', 'TD', '20+', '40+', 'LNG', 'Rec 1st', '1st%', 'Rec FUM', 'Rec YAC/R', 'Tgts']

In [88]:
df3 = pd.DataFrame(columns = find_header)
df3

Empty DataFrame
Columns: [Player, Rec, Yds, TD, 20+, 40+, LNG, Rec 1st, 1st%, Rec FUM, Rec YAC/R, Tgts]
Index: []

In [90]:
#find_content = soup.find_all('tr')
#print(find_content)
column_data = soup.find_all('tr')
#column_data

In [92]:
for row in column_data[1:]: #For Loop that skips the first row (headers)
    row_data = row.find_all('td') #We get the information contained inside the td brackets
    individual_row_data = [data.text.strip() for data in row_data] # Creating a list using a nested for loop to get each element in the table
    #print(individual_row_data)
    length = len(df3) #We get the length of the dataframe to add the information obtained to the end of the dataframe 
    df3.loc[length] = individual_row_data # in order to not replace the existing one

### Printing our DataFrames to see everything is in order.

In [31]:
df

,Player,Pass Yds,Yds/Att,Att,Cmp,Cmp %,TD,INT,Rate,1st,1st%,20+,40+,Lng,Sck,SckY
0,Lamar Jackson,3053,8.9,343,231,67.4,27,3,117.9,143,41.7,41,10,84,16,96
1,Geno Smith,3035,7.5,405,280,69.1,12,12,88.4,149,36.8,33,4,71,37,241
2,Joe Burrow,3028,7.4,408,274,67.2,27,4,106.9,155,38,33,10,70,26,138
3,C.J. Stroud,2875,7.3,396,250,63.1,14,9,87.3,144,36.4,33,5,67,39,303
4,Kirk Cousins,2807,7.8,360,245,68.1,17,9,96.6,129,35.8,34,5,52,23,165
5,Matthew Stafford,2800,7.3,385,256,66.5,15,7,93.2,131,34,34,4,69,26,196
6,Baker Mayfield,2799,7.5,374,267,71.4,24,9,104.1,143,38.2,32,2,55,24,143
7,Jared Goff,2761,9,306,223,72.9,20,9,109.9,134,43.8,41,8,70,21,163
8,Sam Darnold,2717,8.3,327,221,67.6,21,10,101.7,126,38.5,43,7,97,31,202
9,Patrick Mahomes,2673,7,381,266,69.8,18,11,93.2,148,38.8,28,3,54,27,182
10,Jayden Daniels,2613,7.9,332,227,68.4,12,5,97.6,120,36.1,35,8,86,27,139
11,Brock Purdy,2613,8.5,306,202,66,13,8,95.9,121,39.5,36,9,76,20,95
12,Bo Nix,2548,6.4,399,259,64.9,16,6,89.9,115,28.8,39,2,49,19,158
13,Josh Allen,2543,7.5,339,217,64,18,5,98.2,117,34.5,38,7,63,13,61
14,Aaron Rodgers,2442,6.4,380,241,63.4,17,7,89,121,31.8,34,2,57,26,199
15,Justin Herbert,2404,7.7,313,197,62.9,13,1,99,106,33.9,35,4,66,27,148
16,Jalen Hurts,2376,8.3,285,197,69.1,13,5,102.3,109,38.2,36,10,67,29,220
17,Caleb Williams,2356,6.3,372,233,62.6,11,5,84.9,111,29.8,26,5,47,44,298
18,Kyler Murray,2343,7.5,313,215,68.7,12,4,98,114,36.4,27,2,60,20,124
19,Jordan Love,2244,8,280,173,61.8,18,11,92,100,35.7,32,9,70,10,70
20,Daniel Jones,2070,6.1,341,216,63.3,8,7,79.4,106,31.1,19,2,43,29,172
21,Gardner Minshew,2013,6.6,306,203,66.3,9,10,81,106,34.6,22,2,57,29,164
22,Trevor Lawrence,2004,7.3,274,168,61.3,11,6,87.9,96,35,31,4,85,18,140
23,Dak Prescott,1978,6.9,286,185,64.7,11,8,86,87,30.4,23,3,65,21,112
24,Tua Tagovailoa,1760,7.6,232,170,73.3,13,4,106.2,96,41.4,19,3,80,13,101

In [78]:
df2

,Player,Rush Yds,Att,TD,20+,40+,Lng,Rush 1st,Rush 1st%,Rush FUM
0,Saquon Barkley,1392,223,10,12,6,72,53,23.8,1
1,Derrick Henry,1325,221,13,14,3,87,60,27.2,3
2,Josh Jacobs,944,202,7,6,0,38,47,23.3,2
3,Jahmyr Gibbs,886,154,10,7,2,70,41,26.6,0
4,Chuba Hubbard,876,177,7,6,0,38,45,25.4,0
5,Kyren Williams,822,207,9,2,0,30,56,27,5
6,Tony Pollard,800,184,4,5,1,41,37,20.1,0
7,Aaron Jones,798,179,3,3,1,41,33,18.4,2
8,Joe Mixon,786,185,10,6,2,59,37,20,0
9,Bijan Robinson,783,167,6,3,0,37,38,22.8,0
10,Alvin Kamara,782,183,6,3,0,24,45,24.6,0
11,J.K. Dobbins,766,158,8,6,3,61,39,24.7,0
12,Najee Harris,749,191,3,6,0,36,36,18.8,0
13,Jordan Mason,711,140,3,8,0,38,32,22.9,3
14,Jonathan Taylor,708,161,5,7,1,58,34,21.1,0
15,James Conner,705,166,5,3,0,22,46,27.7,1
16,D'Andre Swift,665,168,5,5,1,56,26,15.5,1
17,Breece Hall,632,152,4,3,1,42,27,17.8,3
18,David Montgomery,632,145,11,1,0,21,43,29.7,2
19,Chase Brown,607,140,5,5,0,30,25,17.9,2
20,Lamar Jackson,599,103,3,4,0,33,31,30.1,3
21,Rhamondre Stevenson,598,162,6,1,0,33,30,18.5,4
22,James Cook,596,137,10,2,1,49,33,24.1,0
23,Tyrone Tracy Jr.,587,116,3,5,1,45,28,24.1,2
24,Bucky Irving,579,108,5,4,1,56,28,25.9,2

In [95]:
df3

,Player,Rec,Yds,TD,20+,40+,LNG,Rec 1st,1st%,Rec FUM,Rec YAC/R,Tgts
0,CeeDee Lamb,77,841,4,10,2,65,38,49.4,1,353,118
1,Brock Bowers,74,744,3,8,1,57,38,51.4,0,395,99
2,Ja'Marr Chase,73,1056,12,13,6,70,47,64.4,0,481,100
3,Amon-Ra St. Brown,71,747,9,8,0,35,47,66.2,0,246,85
4,Garrett Wilson,69,722,5,11,0,35,40,58,1,282,108
5,Travis Kelce,68,569,2,7,0,38,30,44.1,2,232,88
6,Malik Nabers,67,671,3,8,0,39,37,55.2,1,208,103
7,Jaxon Smith-Njigba,66,755,4,8,2,46,37,56.1,1,338,93
8,Justin Jefferson,61,939,5,18,3,97,41,67.2,1,258,91
9,Drake London,61,710,6,4,0,31,39,63.9,0,175,90
10,Trey McBride,61,685,0,6,0,37,35,57.4,0,276,80
11,Wan'Dale Robinson,61,441,2,2,0,23,23,37.7,0,229,89
12,Zay Flowers,57,789,4,15,2,53,36,63.2,0,389,87
13,Courtland Sutton,57,744,5,13,0,37,38,66.7,1,132,95
14,Khalil Shakir,56,599,2,7,1,52,26,46.4,0,460,66
15,Alvin Kamara,55,443,1,5,1,57,14,25.4,1,466,73
16,Cooper Kupp,55,548,5,7,1,69,21,38.2,1,236,77
17,DJ Moore,54,566,4,7,1,44,25,46.3,0,312,80
18,Josh Downs,53,594,4,7,1,69,31,58.5,0,246,78
19,Terry McLaurin,53,823,7,10,5,86,37,69.8,0,229,74
20,Jakobi Meyers,53,579,2,6,0,33,32,60.4,0,170,75
21,George Pickens,52,776,2,14,3,44,32,61.5,1,157,84
22,Hunter Henry,51,535,1,4,0,35,30,58.8,0,212,74
23,Chris Godwin,50,576,5,7,2,55,32,64,1,350,62
24,Cade Otton,50,486,4,5,0,30,26,52,2,237,73

## At last, we import the result obtained as a CSV file to be ready to use for our data analytics project.

In [108]:
df.to_csv(r'C:\Users\julio.lopez1\Downloads\Web Scrapped CSV\NFLMVP2024-QB.csv', index = False)

In [110]:
df2.to_csv(r'C:\Users\julio.lopez1\Downloads\Web Scrapped CSV\NFLMVP2024-RB.csv', index = False)

In [114]:
df3.to_csv(r'C:\Users\julio.lopez1\Downloads\Web Scrapped CSV\NFLMVP2024-WR.csv', index = False)